/** NIH RxNav + OpenFDA Drug Safety Service
 * All upstream calls are proxied through the `drug-reference` edge function
 * to prevent the user's IP and medication lookups from reaching third-party APIs directly.
 * RxNav docs: https://rxnav.nlm.nih.gov/RxNormAPIs.html
 */

import { supabase } from '@/shared/lib/supabase'

export interface DrugInteraction {
  severity: 'high' | 'moderate' | 'low'
  description: string
  drug1: string
  drug2: string
}

export interface OpenFDALabelData {
  foodInteractions?: string
  contraindications?: string
}

function cleanText(text: string | undefined): string {
  if (!text) return ''
  return text
    .replace(/<[^>]*>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 500)
}

/** Normalize a drug name to an RxCUI code using NIH RxNav. */
export async function lookupRxCUI(name: string): Promise<string | null> {
  const trimmed = name.trim()
  if (!trimmed) return null

  try {
    const { data, error } = await supabase.functions.invoke('drug-reference', {
      body: { action: 'lookupRxCUI', params: { name: trimmed } },
    })
    if (error) return null
    const typed = data as { idGroup?: { rxnormId?: string[] } }
    return typed?.idGroup?.rxnormId?.[0] ?? null
  } catch {
    return null
  }
}

/** Check for drug-drug interactions between a list of RxCUI codes. */
export async function getDrugInteractions(rxcuis: string[]): Promise<DrugInteraction[]> {
  const valid = rxcuis.filter(Boolean)
  if (valid.length < 2) return []

  try {
    const { data, error } = await supabase.functions.invoke('drug-reference', {
      body: { action: 'getDrugInteractions', params: { rxcuis: valid } },
    })
    if (error) return []

    const typed = data as {
      fullInteractionTypeGroup?: Array<{
        fullInteractionType?: Array<{
          interactionPair?: Array<{
            severity?: string
            description?: string
            interactionConcept?: Array<{
              minConceptItem?: { name?: string }
            }>
          }>
        }>
      }>
    }

    const interactions: DrugInteraction[] = []

    for (const group of typed.fullInteractionTypeGroup ?? []) {
      for (const type of group.fullInteractionType ?? []) {
        for (const pair of type.interactionPair ?? []) {
          const sev = (pair.severity ?? '').toLowerCase()
          const severity: DrugInteraction['severity'] =
            sev.includes('high') || sev.includes('contraindicated')
              ? 'high'
              : sev.includes('moderate')
              ? 'moderate'
              : 'low'
          const drug1 = pair.interactionConcept?.[0]?.minConceptItem?.name ?? ''
          const drug2 = pair.interactionConcept?.[1]?.minConceptItem?.name ?? ''
          const description = pair.description ?? ''
          if (description) {
            interactions.push({ severity, description, drug1, drug2 })
          }
        }
      }
    }

    // Deduplicate by description
    const seen = new Set<string>()
    return interactions.filter((i) => {
      if (seen.has(i.description)) return false
      seen.add(i.description)
      return true
    })
  } catch {
    return []
  }
}

/**
 * Look up the active ingredient names for a drug by RxCUI.
 * Used for ingredient-level allergy checking.
 */
export async function getIngredients(rxcui: string): Promise<string[]> {
  if (!rxcui) return []
  try {
    const { data, error } = await supabase.functions.invoke('drug-reference', {
      body: { action: 'getIngredients', params: { rxcui } },
    })
    if (error) return []
    const typed = data as {
      relatedGroup?: {
        relatedByRelationship?: Array<{
          conceptGroup?: Array<{
            conceptProperties?: Array<{ name?: string }>
          }>
        }>
      }
    }
    const names: string[] = []
    for (const rel of typed.relatedGroup?.relatedByRelationship ?? []) {
      for (const grp of rel.conceptGroup ?? []) {
        for (const prop of grp.conceptProperties ?? []) {
          if (prop.name) names.push(prop.name)
        }
      }
    }
    return names
  } catch {
    return []
  }
}

/**
 * Fetch the missed-dose instructions for a drug from the OpenFDA label.
 * Returns a human-readable string or null if unavailable.
 *
 * The returned text is the raw `missed_dose` field from the FDA-approved
 * prescribing information (structured product labeling). It is displayed in the
 * UI with explicit source attribution and a professional-consultation disclaimer
 * so that users understand this is regulatory label text, not clinical advice
 * generated by the app.
 */
export async function getCatchUpGuidance(rxcui: string): Promise<string | null> {
  if (!rxcui) return null
  try {
    const { data, error } = await supabase.functions.invoke('drug-reference', {
      body: { action: 'getCatchUpGuidance', params: { rxcui } },
    })
    if (error) return null
    const typed = data as {
      results?: Array<{
        missed_dose?: string[]
        do_not_use?: string[]
      }>
    } | null
    if (!typed) return null
    const label = typed.results?.[0]
    if (!label) return null
    const raw = label.missed_dose?.[0]
    if (!raw) return null
    return cleanText(raw)
  } catch {
    return null
  }
}

/** Fetch food interactions and contraindications for a drug from OpenFDA label endpoint. */
export async function getOpenFDALabel(rxcui: string): Promise<OpenFDALabelData> {
  if (!rxcui) return {}

  try {
    const { data, error } = await supabase.functions.invoke('drug-reference', {
      body: { action: 'getOpenFDALabel', params: { rxcui } },
    })
    if (error) return {}
    const typed = data as {
      results?: Array<{
        food_and_drug_interaction?: string[]
        contraindications?: string[]
      }>
    } | null
    if (!typed) return {}
    const label = typed.results?.[0]
    if (!label) return {}
    return {
      foodInteractions: cleanText(label.food_and_drug_interaction?.[0]),
      contraindications: cleanText(label.contraindications?.[0]),
    }
  } catch {
    return {}
  }
}
